name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore HogwartsBattle.sln
      - name: Build
        run: dotnet build HogwartsBattle.sln --configuration Release --no-restore
      - name: Publish Server
        run: dotnet publish HogwartsBattle.Server/HogwartsBattle.Server.csproj -c Release -o out
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-publish
          path: out